// Code generated by MockGen. DO NOT EDIT.
// Source: go-app/app (interfaces: KeeperCatalog)

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	schema "go-app/schema"
	reflect "reflect"
)

// MockKeeperCatalog is a mock of KeeperCatalog interface
type MockKeeperCatalog struct {
	ctrl     *gomock.Controller
	recorder *MockKeeperCatalogMockRecorder
}

// MockKeeperCatalogMockRecorder is the mock recorder for MockKeeperCatalog
type MockKeeperCatalogMockRecorder struct {
	mock *MockKeeperCatalog
}

// NewMockKeeperCatalog creates a new mock instance
func NewMockKeeperCatalog(ctrl *gomock.Controller) *MockKeeperCatalog {
	mock := &MockKeeperCatalog{ctrl: ctrl}
	mock.recorder = &MockKeeperCatalogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockKeeperCatalog) EXPECT() *MockKeeperCatalogMockRecorder {
	return m.recorder
}

// CreateCatalog mocks base method
func (m *MockKeeperCatalog) CreateCatalog(arg0 *schema.CreateCatalogOpts) (*schema.CreateCatalogResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCatalog", arg0)
	ret0, _ := ret[0].(*schema.CreateCatalogResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCatalog indicates an expected call of CreateCatalog
func (mr *MockKeeperCatalogMockRecorder) CreateCatalog(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCatalog", reflect.TypeOf((*MockKeeperCatalog)(nil).CreateCatalog), arg0)
}

// EditCatalog mocks base method
func (m *MockKeeperCatalog) EditCatalog(arg0 *schema.EditCatalogOpts) (*schema.CreateCatalogResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditCatalog", arg0)
	ret0, _ := ret[0].(*schema.CreateCatalogResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditCatalog indicates an expected call of EditCatalog
func (mr *MockKeeperCatalogMockRecorder) EditCatalog(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditCatalog", reflect.TypeOf((*MockKeeperCatalog)(nil).EditCatalog), arg0)
}
