// Code generated by MockGen. DO NOT EDIT.
// Source: go-app/app (interfaces: KeeperCatalog)

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	schema "go-app/schema"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
	reflect "reflect"
)

// MockKeeperCatalog is a mock of KeeperCatalog interface
type MockKeeperCatalog struct {
	ctrl     *gomock.Controller
	recorder *MockKeeperCatalogMockRecorder
}

// MockKeeperCatalogMockRecorder is the mock recorder for MockKeeperCatalog
type MockKeeperCatalogMockRecorder struct {
	mock *MockKeeperCatalog
}

// NewMockKeeperCatalog creates a new mock instance
func NewMockKeeperCatalog(ctrl *gomock.Controller) *MockKeeperCatalog {
	mock := &MockKeeperCatalog{ctrl: ctrl}
	mock.recorder = &MockKeeperCatalogMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockKeeperCatalog) EXPECT() *MockKeeperCatalogMockRecorder {
	return m.recorder
}

// AddVariant mocks base method
func (m *MockKeeperCatalog) AddVariant(arg0 primitive.ObjectID, arg1 *schema.AddVariantOpts) (*schema.CreateVariantResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddVariant", arg0, arg1)
	ret0, _ := ret[0].(*schema.CreateVariantResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddVariant indicates an expected call of AddVariant
func (mr *MockKeeperCatalogMockRecorder) AddVariant(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddVariant", reflect.TypeOf((*MockKeeperCatalog)(nil).AddVariant), arg0, arg1)
}

// CreateCatalog mocks base method
func (m *MockKeeperCatalog) CreateCatalog(arg0 *schema.CreateCatalogOpts) (*schema.CreateCatalogResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCatalog", arg0)
	ret0, _ := ret[0].(*schema.CreateCatalogResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCatalog indicates an expected call of CreateCatalog
func (mr *MockKeeperCatalogMockRecorder) CreateCatalog(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCatalog", reflect.TypeOf((*MockKeeperCatalog)(nil).CreateCatalog), arg0)
}

// EditCatalog mocks base method
func (m *MockKeeperCatalog) EditCatalog(arg0 *schema.EditCatalogOpts) (*schema.EditCatalogResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditCatalog", arg0)
	ret0, _ := ret[0].(*schema.EditCatalogResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditCatalog indicates an expected call of EditCatalog
func (mr *MockKeeperCatalogMockRecorder) EditCatalog(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditCatalog", reflect.TypeOf((*MockKeeperCatalog)(nil).EditCatalog), arg0)
}

// GetBasicCatalogInfo mocks base method
func (m *MockKeeperCatalog) GetBasicCatalogInfo(arg0 *schema.GetBasicCatalogFilter) ([]schema.GetBasicCatalogResp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBasicCatalogInfo", arg0)
	ret0, _ := ret[0].([]schema.GetBasicCatalogResp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBasicCatalogInfo indicates an expected call of GetBasicCatalogInfo
func (mr *MockKeeperCatalogMockRecorder) GetBasicCatalogInfo(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBasicCatalogInfo", reflect.TypeOf((*MockKeeperCatalog)(nil).GetBasicCatalogInfo), arg0)
}
