[server]
listenAddr="localhost"
port="8000"
readTimeout=5
writeTimeout=5
closeTimeout=5
env="dev"
useMemoryStore=true

[api]
mode="dev"
enableTestRoute=true 
enableMediaRoute=true
enableStaticRoute=true
maxRequestDataSize=1048576

[token]
jwtSignKey="abc123"
expiresAt=150

[kafka]
brokerDial="tcp"
brokerUrl="localhost"
brokerPort="29092"

[logger]

    [logger.fileLog]
    enableFileLog=false

    [logger.kafkaLog]
    enableKafkaLog=false
    kafkaTopic="log"
    kafkaParition=1

    [logger.consoleLog]
    enableConsoleLog=true
    maxBackupFile=1
    maxFileSize=1 #megabytes
    maxAge=1 #days
    compress=true #disabled by default

[database]
scheme="mongodb+srv"
username="vasu"
password="admin123"
host="cluster0-tyaml.mongodb.net"
replicaSet="Cluster0-shard-0"

[redis]
network="tcp"
host="localhost"
port="6379"
password=""
username=""

[middleware]
enableRequestLog=false

[ivs]
region="eu-west-1"
authorizeChannel=false
latencyMode="LOW"
channelType="STANDARD"

[app]

    [app.media]
    dbName="test_content"

    [app.content]
    dbName="test_content"

    [app.live]
    dbName="test_content"

    [app.liveCommentProducer]
    brokers=["localhost:9092"]
    topic="liveComment"
    async=false

    [app.liveCommentConsumer]
    brokers=["localhost:9092"]
    topic="liveComment"
    groupID="liveComment1"

[elasticsearch]
endpoint="https://search-hypd-store-v2-dev-hdz3iw7so7oenedrzfgrpxi5ym.ap-south-1.es.amazonaws.com"
username="admin"
password="Admin@1234"