// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ApplicableON applicable o n
//
// swagger:model ApplicableON
type ApplicableON struct {

	// i ds
	IDs []ObjectID `json:"ids"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this applicable o n
func (m *ApplicableON) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateIDs(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ApplicableON) validateIDs(formats strfmt.Registry) error {
	if swag.IsZero(m.IDs) { // not required
		return nil
	}

	for i := 0; i < len(m.IDs); i++ {

		if err := m.IDs[i].Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ids" + "." + strconv.Itoa(i))
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("ids" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

// ContextValidate validate this applicable o n based on the context it is used
func (m *ApplicableON) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateIDs(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ApplicableON) contextValidateIDs(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.IDs); i++ {

		if err := m.IDs[i].ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("ids" + "." + strconv.Itoa(i))
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("ids" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *ApplicableON) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ApplicableON) UnmarshalBinary(b []byte) error {
	var res ApplicableON
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
