// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CommonError common error
//
// swagger:model CommonError
type CommonError struct {

	// Message of the error
	// in: string
	Message string `json:"message,omitempty"`

	// Status of the error
	Status int64 `json:"status,omitempty"`
}

// Validate validates this common error
func (m *CommonError) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this common error based on context it is used
func (m *CommonError) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CommonError) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CommonError) UnmarshalBinary(b []byte) error {
	var res CommonError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
