// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// CurrencyISO CurrencyISO iso representation of currency
//
// swagger:model CurrencyISO
type CurrencyISO string

// Validate validates this currency i s o
func (m CurrencyISO) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this currency i s o based on context it is used
func (m CurrencyISO) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
