// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ETA ETA contains maximum and minimum delivery time of a catalog
//
// swagger:model ETA
type ETA struct {

	// max
	Max int64 `json:"max,omitempty"`

	// min
	Min int64 `json:"min,omitempty"`

	// unit
	Unit string `json:"unit,omitempty"`
}

// Validate validates this e t a
func (m *ETA) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this e t a based on context it is used
func (m *ETA) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ETA) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ETA) UnmarshalBinary(b []byte) error {
	var res ETA
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
