// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// EmailLoginCustomerResp email login customer resp
//
// swagger:model EmailLoginCustomerResp
type EmailLoginCustomerResp struct {

	// Token after successful login
	Token string `json:"token,omitempty"`
}

// Validate validates this email login customer resp
func (m *EmailLoginCustomerResp) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this email login customer resp based on context it is used
func (m *EmailLoginCustomerResp) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EmailLoginCustomerResp) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EmailLoginCustomerResp) UnmarshalBinary(b []byte) error {
	var res EmailLoginCustomerResp
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
