// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IMG IMG contains image url, src, height and id
//
// swagger:model IMG
type IMG struct {

	// height
	Height int64 `json:"height,omitempty"`

	// s r c
	SRC string `json:"src,omitempty"`

	// width
	Width int64 `json:"width,omitempty"`
}

// Validate validates this i m g
func (m *IMG) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this i m g based on context it is used
func (m *IMG) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IMG) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IMG) UnmarshalBinary(b []byte) error {
	var res IMG
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
