// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Img img
//
// swagger:model Img
type Img struct {

	// s r c
	SRC string `json:"src,omitempty"`
}

// Validate validates this img
func (m *Img) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this img based on context it is used
func (m *Img) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Img) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Img) UnmarshalBinary(b []byte) error {
	var res Img
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
