// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// ObjectID ObjectID is the BSON ObjectID type.
//
// swagger:model ObjectID
type ObjectID []uint8

// Validate validates this object ID
func (m ObjectID) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this object ID based on context it is used
func (m ObjectID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
