// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PhoneNoOpts phone no opts
//
// swagger:model PhoneNoOpts
type PhoneNoOpts struct {

	// Number of the user
	// in: string
	Number string `json:"number,omitempty"`

	// Prefix of the number
	// in: string
	Prefix string `json:"prefix,omitempty"`
}

// Validate validates this phone no opts
func (m *PhoneNoOpts) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this phone no opts based on context it is used
func (m *PhoneNoOpts) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PhoneNoOpts) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PhoneNoOpts) UnmarshalBinary(b []byte) error {
	var res PhoneNoOpts
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
