// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SocialMedia SocialMedia contains followers_count for a specific account
//
// Type -> facebook
// > twitter
// > youtube
// > instagram
//
// swagger:model SocialMedia
type SocialMedia struct {

	// followers count
	FollowersCount uint64 `json:"followers_count,omitempty"`

	// URL
	URL string `json:"url,omitempty"`
}

// Validate validates this social media
func (m *SocialMedia) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this social media based on context it is used
func (m *SocialMedia) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SocialMedia) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SocialMedia) UnmarshalBinary(b []byte) error {
	var res SocialMedia
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
