// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Tax tax
//
// swagger:model Tax
type Tax struct {

	// rate
	Rate float32 `json:"rate,omitempty"`

	// tax ranges
	TaxRanges []*TaxRange `json:"tax_ranges"`

	// type
	Type string `json:"type,omitempty"`
}

// Validate validates this tax
func (m *Tax) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTaxRanges(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Tax) validateTaxRanges(formats strfmt.Registry) error {
	if swag.IsZero(m.TaxRanges) { // not required
		return nil
	}

	for i := 0; i < len(m.TaxRanges); i++ {
		if swag.IsZero(m.TaxRanges[i]) { // not required
			continue
		}

		if m.TaxRanges[i] != nil {
			if err := m.TaxRanges[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("tax_ranges" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("tax_ranges" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this tax based on the context it is used
func (m *Tax) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateTaxRanges(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Tax) contextValidateTaxRanges(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.TaxRanges); i++ {

		if m.TaxRanges[i] != nil {
			if err := m.TaxRanges[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("tax_ranges" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("tax_ranges" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *Tax) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Tax) UnmarshalBinary(b []byte) error {
	var res Tax
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
