// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// TaxRange tax range
//
// swagger:model TaxRange
type TaxRange struct {

	// max value
	MaxValue int64 `json:"max_value,omitempty"`

	// min value
	MinValue int64 `json:"min_value,omitempty"`

	// rate
	Rate float32 `json:"rate,omitempty"`
}

// Validate validates this tax range
func (m *TaxRange) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this tax range based on context it is used
func (m *TaxRange) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TaxRange) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TaxRange) UnmarshalBinary(b []byte) error {
	var res TaxRange
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
